---
- name: Install kubeadm on worker nodes
  yum:
    name: "{{ item }}"
    state: present
  loop:
  - kubeadm
  - kubelet
  when: inventory_hostname in groups["worker_nodes"]

- name: Start the kubelet service
  systemd:
    name: kubelet
    state: started
  when: inventory_hostname in groups["worker_nodes"]

- name: Generate token to join worker nodes
  shell: kubeadm token create --print-join-command > /root/token
  when: inventory_hostname in groups["master_nodes"]

- name: Copy the token to ansible master node
  fetch:
    src: /root/token
    dest: /tmp/token
    flat: yes
  when: inventory_hostname in groups["master_nodes"]

- name: Set the token variable
  set_fact:
    token: "{{ lookup('file','/tmp/token') }}"
    when: inventory_hostname in groups['worker_nodes']

- name: Run join command on worker node
  shell: "{{ token }}"
  when: inventory_hostname in groups["worker_nodes"]


